apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-worker
  namespace: demo
spec:
  scaleTargetRef:
    name: demo-worker
  pollingInterval: 10
  cooldownPeriod: 15
  minReplicaCount: 0
  maxReplicaCount: 30
  advanced:
    horizontalPodAutoscalerConfig:
      name: demo-worker
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
          - type: Percent
            value: 100
            periodSeconds: 30
          - type: Pods
            value: 6
            periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 15
          selectPolicy: Max
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 30
            periodSeconds: 15
  triggers:
  - type: redis
    metadata:
      address: redis.demo.svc.cluster.local:6379
      listName: demo-jobs
      listLength: "20"
      activationListLength: "5"
      enableTLS: "false"
